<?= $this->extend('mentor/layout') ?>
<?= $this->section('content') ?>
<style>
    .absensi-hero{background:linear-gradient(125deg,#24123f,#6135a5);border-radius:22px;color:#fff;overflow:hidden;position:relative}.absensi-hero:after{content:'';position:absolute;width:250px;height:250px;border:38px solid rgba(255,255,255,.08);border-radius:50%;right:-65px;top:-125px}.absensi-hero>*{position:relative;z-index:1}.absensi-panel{border:1px solid #ece6f4;border-radius:18px;box-shadow:0 9px 25px rgba(37,19,64,.05)}.pertemuan-card{border:1px solid #eee8f4;border-radius:15px;transition:.2s}.pertemuan-card:hover{border-color:#c8afe7;box-shadow:0 8px 20px rgba(79,45,128,.08)}.pertemuan-number{align-items:center;background:#f0e8fb;border-radius:13px;color:#7042b4;display:flex;font-size:1.15rem;font-weight:700;height:48px;justify-content:center;width:48px}.status-hadir{background:#e5f7ed;color:#167345}.status-belum{background:#fff4d9;color:#936b00}.btn-absen{background:linear-gradient(135deg,#7042b4,#8d5ccc);border:0;border-radius:10px;color:#fff;font-weight:600}.btn-absen:hover{background:linear-gradient(135deg,#5e349d,#794bc4);color:#fff}
</style>

<div class="d-flex justify-content-between align-items-center mb-4 gap-3"><div><h3 class="fw-bold mb-1">Absensi Mengajar</h3><p class="text-muted mb-0"><i class="fa-solid fa-book-open me-1" style="color:#794bc4"></i><?= esc($kelas['nama_kelas']) ?></p></div><a class="btn btn-outline-secondary" href="<?= base_url('mentor/kelas/' . $kelas['id_kelas']) ?>"><i class="fa-solid fa-arrow-left me-1"></i> Kembali</a></div>

<section class="absensi-hero p-4 p-lg-5 mb-4"><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-4"><div><span class="badge rounded-pill text-bg-light text-primary mb-3">CATAT KEHADIRAN</span><h4 class="fw-bold mb-2">Absensi setiap sesi mengajar</h4><p class="mb-0 opacity-75">Absensi yang Anda isi akan langsung tercatat pada monitoring Admin.</p></div><div class="fs-1 opacity-75"><i class="fa-solid fa-calendar-check"></i></div></div></section>

<div id="sesi" class="absensi-panel bg-white p-4 mb-4"><div class="d-flex align-items-center gap-3 mb-3"><div class="pertemuan-number"><i class="fa-solid fa-layer-group"></i></div><div><h5 class="fw-bold mb-1">Tambah Sesi Materi</h5><p class="text-muted small mb-0">Buat jadwal pertemuan sekaligus tambahkan bahan materi untuk peserta.</p></div></div><form action="<?= base_url('mentor/kelas/' . $kelas['id_kelas'] . '/absensi/sesi') ?>" method="post" enctype="multipart/form-data"><div class="row g-3 align-items-end"><div class="col-sm-3"><label class="form-label fw-semibold">Pertemuan ke-</label><input type="number" name="pertemuan_ke" class="form-control" min="1" placeholder="1" required></div><div class="col-sm-5"><label class="form-label fw-semibold">Topik sesi mengajar</label><input type="text" name="materi" class="form-control" placeholder="Contoh: Dasar Fotografi" required></div><div class="col-sm-4"><label class="form-label fw-semibold">Tanggal & jam mengajar</label><input type="datetime-local" name="tanggal_kbm" class="form-control" required></div><div class="col-sm-6"><label class="form-label fw-semibold">Judul materi</label><input type="text" name="judul_materi" class="form-control" placeholder="Contoh: Modul Pertemuan 1" required></div><div class="col-sm-3"><label class="form-label fw-semibold">Jenis</label><select name="tipe_materi" class="form-select"><option>Dokumen</option><option>Video</option><option>Modul</option></select></div><div class="col-sm-3"><label class="form-label fw-semibold">File materi</label><input type="file" name="file_materi" class="form-control"></div><div class="col-sm-8"><label class="form-label fw-semibold">Tautan materi <span class="text-muted fw-normal">(opsional jika file diisi)</span></label><input type="url" name="url_materi" class="form-control" placeholder="https://..."></div><div class="col-sm-4"><button class="btn btn-absen w-100"><i class="fa-solid fa-plus me-1"></i> Simpan Sesi Materi</button></div></div></form></div>

<div id="mentor" class="absensi-panel bg-white p-4"><div class="d-flex justify-content-between align-items-center mb-4"><div><h5 class="fw-bold mb-1">Absensi Mentor</h5><p class="text-muted small mb-0">Catat kehadiran Anda pada setiap pertemuan mengajar.</p></div><span class="badge rounded-pill text-bg-light text-primary px-3 py-2"><?= count($jadwal ?? []) ?> pertemuan</span></div>
    <?php if (empty($jadwal)): ?>
        <div class="text-center text-muted py-5"><i class="fa-regular fa-calendar-xmark fs-1 mb-3"></i><h5 class="fw-bold">Belum ada jadwal mengajar</h5><p class="mb-0">Jadwal pertemuan akan tampil setelah Admin menambahkannya.</p></div>
    <?php else: ?>
        <div class="d-grid gap-3">
            <?php foreach ($jadwal as $item): ?>
                <?php $sudahAbsen = !empty($item['id_absensi']); ?>
                <?php $sesiDibuka = (int) ($item['absensi_dibuka'] ?? 0) === 1 && !empty($item['absensi_selesai']) && strtotime($item['absensi_selesai']) > time(); ?>
                <?php $mentorSudahAbsen = !empty($item['id_absensi']) && ($item['status_absen'] ?? '') === 'hadir'; ?>
                <div class="pertemuan-card p-3 p-md-4"><div class="d-flex flex-column flex-md-row align-items-md-center gap-3"><div class="pertemuan-number">#<?= esc($item['pertemuan_ke'] ?? '-') ?></div><div class="flex-grow-1"><div class="d-flex flex-wrap align-items-center gap-2 mb-1"><h6 class="fw-bold mb-0">Pertemuan <?= esc($item['pertemuan_ke'] ?? '-') ?></h6><span class="badge rounded-pill <?= $mentorSudahAbsen ? 'status-hadir' : 'status-belum' ?>"><?= $mentorSudahAbsen ? 'Mentor Sudah Absen' : 'Mentor Belum Absen' ?></span><?php if ($sesiDibuka): ?><span class="badge rounded-pill status-hadir">Sesi Peserta Dibuka</span><?php endif; ?></div><div class="text-muted small mb-1"><i class="fa-solid fa-book me-1"></i><?= esc($item['materi'] ?: 'Materi belum ditentukan') ?></div><div class="text-muted small"><i class="fa-regular fa-calendar me-1"></i><?= !empty($item['tanggal_kbm']) ? esc(date('d M Y, H:i', strtotime($item['tanggal_kbm']))) : 'Tanggal belum ditentukan' ?></div><?php if ($sesiDibuka): ?><div class="text-success small mt-1"><i class="fa-solid fa-clock me-1"></i>Peserta dapat absen pukul <?= esc(date('H:i', strtotime($item['absensi_mulai']))) ?> - <?= esc(date('H:i', strtotime($item['absensi_selesai']))) ?></div><?php endif; ?></div><div class="flex-shrink-0 d-flex flex-column gap-2"><?php if (! $mentorSudahAbsen): ?><form action="<?= base_url('mentor/kelas/' . $kelas['id_kelas'] . '/absensi/' . $item['id_jadwal_kelas']) ?>" method="post"><button class="btn btn-absen btn-sm text-nowrap"><i class="fa-solid fa-fingerprint me-1"></i> Absen Mentor</button></form><?php elseif ($sesiDibuka): ?><form action="<?= base_url('mentor/kelas/' . $kelas['id_kelas'] . '/absensi/' . $item['id_jadwal_kelas'] . '/tutup') ?>" method="post"><button class="btn btn-outline-danger btn-sm"><i class="fa-solid fa-lock me-1"></i> Tutup Sesi Peserta</button></form><?php else: ?><form action="<?= base_url('mentor/kelas/' . $kelas['id_kelas'] . '/absensi/' . $item['id_jadwal_kelas'] . '/buka') ?>" method="post" class="d-flex flex-wrap gap-2"><input type="time" name="jam_mulai_absensi" class="form-control form-control-sm" required aria-label="Jam mulai absensi"><span class="align-self-center text-muted small">sampai</span><input type="time" name="jam_selesai_absensi" class="form-control form-control-sm" required aria-label="Jam selesai absensi"><button class="btn btn-absen btn-sm text-nowrap"><i class="fa-solid fa-lock-open me-1"></i> Buka Sesi Peserta</button></form><?php endif; ?></div></div></div>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>
<div id="peserta" class="absensi-panel bg-white p-4 mt-4"><div class="d-flex justify-content-between align-items-center mb-4"><div><h5 class="fw-bold mb-1">Jadwal Absensi Peserta</h5><p class="text-muted small mb-0">Buka dan batasi waktu absensi peserta pada setiap pertemuan.</p></div><i class="fa-solid fa-users" style="color:#7942b4"></i></div>
    <?php if (empty($pesertaAbsensi)): ?>
        <div class="text-center text-muted py-4"><i class="fa-solid fa-user-clock fs-2 mb-2"></i><p class="mb-0">Belum ada peserta aktif atau data absensi peserta.</p></div>
    <?php else: ?>
        <?php $pertemuanAktif = null; ?>
        <?php foreach ($pesertaAbsensi as $peserta): ?>
            <?php if ($pertemuanAktif !== $peserta['id_jadwal_kelas']): ?>
                <?php if ($pertemuanAktif !== null): ?></tbody></table></div></div><?php endif; ?>
                <?php $pertemuanAktif = $peserta['id_jadwal_kelas']; ?>
                <div class="border rounded-3 p-3 mb-3"><div class="d-flex justify-content-between align-items-center mb-3"><h6 class="fw-bold mb-0">Pertemuan <?= esc($peserta['pertemuan_ke']) ?></h6><span class="badge rounded-pill text-bg-light text-primary">Daftar peserta</span></div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Peserta</th><th>Email</th><th>Status</th><th>Waktu Absen</th></tr></thead><tbody>
            <?php endif; ?>
            <tr><td class="fw-semibold"><?= esc($peserta['nama_peserta']) ?></td><td><?= esc($peserta['email']) ?></td><td><?php if (($peserta['status'] ?? null) === 'hadir'): ?><span class="badge rounded-pill bg-success-subtle text-success">Hadir</span><?php else: ?><span class="badge rounded-pill bg-secondary-subtle text-secondary">Belum Absen</span><?php endif; ?></td><td class="text-muted small"><?= !empty($peserta['waktu_absen']) ? esc(date('d M Y, H:i', strtotime($peserta['waktu_absen']))) : '-' ?></td></tr>
        <?php endforeach; ?>
        <?php if ($pertemuanAktif !== null): ?></tbody></table></div></div><?php endif; ?>
    <?php endif; ?>
</div>
<?= $this->endSection() ?>
