<?= $this->extend('mentor/layout') ?>
<?= $this->section('content') ?>
<style>
	.materi-heading{background:linear-gradient(125deg,#24123f,#6135a5);border-radius:20px;color:#fff;overflow:hidden;position:relative}.materi-heading:after{content:'';position:absolute;width:230px;height:230px;border:36px solid rgba(255,255,255,.08);border-radius:50%;right:-60px;top:-125px}.materi-heading>*{position:relative;z-index:1}.materi-panel{border:1px solid #ece6f4;border-radius:20px;box-shadow:0 10px 28px rgba(37,19,64,.06)}.materi-panel-header{border-bottom:1px solid #eee9f4}.field-label{font-size:.8rem;font-weight:700;color:#3c3148;margin-bottom:.5rem}.field-help{font-size:.78rem;color:#8a819a}.materi-form-control{border:1px solid #ded5e9;border-radius:11px;padding:.78rem 1rem}.materi-form-control:focus{border-color:#8d5ccc;box-shadow:0 0 0 .2rem rgba(121,75,196,.12)}.type-option{border:1px solid #e3dced;border-radius:12px;color:#62566f;cursor:pointer;display:block;padding:.75rem;text-align:center;transition:.2s}.type-option:has(input:checked){background:#f2ebfb;border-color:#9062ca;color:#6636a7;box-shadow:0 0 0 2px rgba(121,75,196,.1)}.type-option input{position:absolute;opacity:0}.upload-zone{background:#fbf9fd;border:2px dashed #cfc0e2;border-radius:14px;padding:1.25rem;text-align:center;transition:.2s}.upload-zone:focus-within,.upload-zone:hover{background:#f6f0fc;border-color:#8d5ccc}.upload-zone input{max-width:100%}.btn-admin-purple{background:linear-gradient(135deg,#7042b4,#8d5ccc);border:0;border-radius:11px;color:#fff;font-weight:600;padding:.78rem 1.2rem}.btn-admin-purple:hover{background:linear-gradient(135deg,#5e349d,#794bc4);color:#fff}
</style>

<div class="d-flex justify-content-between align-items-center mb-4 gap-3"><div><h3 class="fw-bold mb-1">Materi Kelas</h3><p class="text-muted mb-0"><i class="fa-solid fa-book-open me-1" style="color:#794bc4"></i><?= esc($kelas['nama_kelas']) ?></p></div><a class="btn btn-outline-secondary" href="<?= base_url('mentor/kelas/' . $kelas['id_kelas']) ?>"><i class="fa-solid fa-arrow-left me-1"></i> Kembali</a></div>
<section class="materi-heading p-4 p-lg-5 mb-4"><div class="d-flex flex-column flex-md-row justify-content-between align-items-md-center gap-4"><div><span class="badge rounded-pill text-bg-light text-primary mb-3">RUANG MATERI</span><h4 class="fw-bold mb-2">Bangun pengalaman belajar yang lebih terarah</h4><p class="mb-0 opacity-75">Tambahkan dokumen, modul, atau video untuk peserta kelas Anda.</p></div><div class="fs-1 opacity-75"><i class="fa-solid fa-layer-group"></i></div></div></section>

<div class="materi-panel bg-white mb-4"><div class="materi-panel-header p-4"><div class="d-flex align-items-center gap-3"><div class="d-flex align-items-center justify-content-center rounded-3" style="width:46px;height:46px;background:#f0e8fb;color:#7042b4"><i class="fa-solid fa-cloud-arrow-up fs-5"></i></div><div><h5 class="fw-bold mb-1">Tambah Materi Baru</h5><p class="text-muted mb-0 small">Lengkapi informasi berikut agar materi mudah ditemukan peserta.</p></div></div></div><div class="p-4">
	<form action="<?= base_url('mentor/kelas/' . $kelas['id_kelas'] . '/materi') ?>" method="post" enctype="multipart/form-data">
		<div class="row g-4">
			<div class="col-lg-7"><label class="field-label" for="judul_materi">Judul materi</label><input id="judul_materi" name="judul_materi" class="form-control materi-form-control" placeholder="Contoh: Modul Dasar Fotografi" required><div class="field-help mt-2">Gunakan judul yang singkat dan mudah dipahami.</div></div>
			<div class="col-lg-5"><div class="field-label">Jenis materi</div><div class="row g-2"><div class="col-4"><label class="type-option"><input type="radio" name="tipe_materi" value="Dokumen" checked><i class="fa-solid fa-file-lines d-block mb-1"></i><small>Dokumen</small></label></div><div class="col-4"><label class="type-option"><input type="radio" name="tipe_materi" value="Video"><i class="fa-solid fa-circle-play d-block mb-1"></i><small>Video</small></label></div><div class="col-4"><label class="type-option"><input type="radio" name="tipe_materi" value="Modul"><i class="fa-solid fa-book d-block mb-1"></i><small>Modul</small></label></div></div></div>
			<div class="col-lg-7"><label class="field-label" for="file_materi">Upload berkas</label><div class="upload-zone"><i class="fa-solid fa-cloud-arrow-up fs-3 mb-2" style="color:#794bc4"></i><div class="fw-semibold mb-1">Pilih berkas materi</div><div class="field-help mb-3">PDF, dokumen, video, atau modul hingga 20 MB</div><input id="file_materi" name="file_materi" type="file" class="form-control materi-form-control"><div id="namaBerkas" class="small text-primary mt-2 d-none"></div></div></div>
			<div class="col-lg-5"><label class="field-label" for="url_materi">Atau gunakan tautan</label><div class="input-group"><span class="input-group-text bg-white" style="border-color:#ded5e9;border-radius:11px 0 0 11px"><i class="fa-solid fa-link" style="color:#794bc4"></i></span><input id="url_materi" name="url_materi" type="url" class="form-control materi-form-control" placeholder="https://..." style="border-radius:0 11px 11px 0"></div><div class="field-help mt-2">Isi jika materi berada di platform eksternal.</div></div>
			<div class="col-12 d-flex flex-column flex-sm-row justify-content-between align-items-sm-center gap-3 pt-2"><span class="field-help"><i class="fa-solid fa-circle-info me-1"></i> Isi salah satu: unggah berkas atau tautan.</span><button class="btn btn-admin-purple"><i class="fa-solid fa-plus me-1"></i> Simpan Materi</button></div>
		</div>
	</form>
</div></div>
<div class="card border-0 shadow-sm"><div class="card-body"><h5 class="fw-bold mb-3">Daftar Materi</h5><?php if (empty($materi)): ?><p class="text-muted mb-0">Belum ada materi.</p><?php endif; ?><?php foreach ($materi as $m): ?><div class="border rounded p-3 mb-3"><form action="<?= base_url('mentor/kelas/' . $kelas['id_kelas'] . '/materi/' . $m['id_materi_kelas']) ?>" method="post" enctype="multipart/form-data"><div class="row g-2 align-items-center"><div class="col-md-4"><input name="judul_materi" class="form-control" value="<?= esc($m['judul_materi']) ?>" required></div><div class="col-md-2"><select name="tipe_materi" class="form-select"><?php foreach (['Dokumen','Video','Modul'] as $tipe): ?><option <?= ($m['tipe_materi'] ?? 'Dokumen') === $tipe ? 'selected' : '' ?>><?= $tipe ?></option><?php endforeach; ?></select></div><div class="col-md-3"><input name="url_materi" type="url" class="form-control" value="<?= esc($m['url_materi'] ?? '') ?>" placeholder="Tautan"></div><div class="col-md-3"><input name="file_materi" type="file" class="form-control"></div><div class="col-12 d-flex justify-content-between align-items-center"><span><?php if (!empty($m['file_materi'])): ?><a target="_blank" href="<?= base_url('uploads/materi/' . rawurlencode($m['file_materi'])) ?>">Lihat file</a><?php elseif (!empty($m['url_materi'])): ?><a target="_blank" href="<?= esc($m['url_materi']) ?>">Buka tautan</a><?php endif; ?></span><span><button class="btn btn-sm btn-outline-primary">Perbarui</button></form><form class="d-inline" action="<?= base_url('mentor/kelas/' . $kelas['id_kelas'] . '/materi/' . $m['id_materi_kelas'] . '/hapus') ?>" method="post" onsubmit="return confirm('Hapus materi ini?')"><button class="btn btn-sm btn-outline-danger">Hapus</button></form></span></div></div></div><?php endforeach; ?></div></div>
<script>
document.getElementById('file_materi')?.addEventListener('change', function () {
	const label = document.getElementById('namaBerkas');
	const nama = this.files?.[0]?.name || '';
	label.textContent = nama ? `Berkas terpilih: ${nama}` : '';
	label.classList.toggle('d-none', !nama);
});
</script>
<?= $this->endSection() ?>
