<?= $this->extend('mentor/layout') ?>
<?= $this->section('content') ?>
<style>
    .assessment-hero{background:linear-gradient(125deg,#24123f,#6135a5);border-radius:22px;color:#fff;overflow:hidden;position:relative}.assessment-hero:after{content:'';position:absolute;width:250px;height:250px;border:38px solid rgba(255,255,255,.08);border-radius:50%;right:-65px;top:-125px}.assessment-hero>*{position:relative;z-index:1}.assessment-panel{border:1px solid #ece6f4;border-radius:18px;box-shadow:0 9px 25px rgba(37,19,64,.05)}
</style>
<div class="d-flex justify-content-between align-items-center mb-4 gap-3"><div><h3 class="fw-bold mb-1">Ujian & Tugas</h3><p class="text-muted mb-0"><i class="fa-solid fa-book-open me-1" style="color:#794bc4"></i><?= esc($kelas['nama_kelas']) ?></p></div><a class="btn btn-outline-secondary" href="<?= base_url('mentor/kelas/' . $kelas['id_kelas']) ?>"><i class="fa-solid fa-arrow-left me-1"></i> Kembali</a></div>
<section class="assessment-hero p-4 p-lg-5 mb-4"><span class="badge rounded-pill text-bg-light text-primary mb-3">EVALUASI PESERTA</span><h4 class="fw-bold mb-2">Tambahkan ujian atau tugas kelas</h4><p class="mb-0 opacity-75">Konten hanya akan tampil untuk peserta yang terdaftar di kelas ini.</p></section>
<?php if (session()->getFlashdata('success')): ?><div class="alert alert-success"><?= esc(session()->getFlashdata('success')) ?></div><?php endif; ?>
<?php if (session()->getFlashdata('error')): ?><div class="alert alert-danger"><?= esc(session()->getFlashdata('error')) ?></div><?php endif; ?>
<div class="assessment-panel bg-white p-4 mb-4"><h5 class="fw-bold mb-3">Buat Konten Baru</h5><form action="<?= base_url('mentor/kelas/' . $kelas['id_kelas'] . '/ujian-tugas') ?>" method="post" enctype="multipart/form-data"><div class="row g-3"><div class="col-md-3"><label class="form-label fw-semibold">Jenis</label><select name="jenis" class="form-select" required><option value="ujian">Ujian</option><option value="tugas">Tugas</option></select></div><div class="col-md-5"><label class="form-label fw-semibold">Judul</label><input name="judul" class="form-control" placeholder="Judul ujian atau tugas" required></div><div class="col-md-4"><label class="form-label fw-semibold">Deadline</label><input name="deadline" type="datetime-local" class="form-control"></div><div class="col-12"><label class="form-label fw-semibold">Keterangan</label><textarea name="keterangan" class="form-control" rows="3" placeholder="Instruksi untuk peserta"></textarea></div><div class="col-md-6"><label class="form-label fw-semibold">File soal ujian <span class="text-muted fw-normal">(opsional)</span></label><input name="file_soal" type="file" class="form-control" accept=".pdf,.doc,.docx"></div><div class="col-12"><button class="btn btn-primary"><i class="fa-solid fa-plus me-1"></i> Tambahkan ke Kelas</button></div></div></form></div>
<div class="row g-4"><div class="col-lg-6"><div class="assessment-panel bg-white p-4 h-100"><h5 class="fw-bold mb-3"><i class="fa-solid fa-pen-to-square me-2 text-primary"></i>Daftar Ujian</h5><?php if (empty($ujian)): ?><p class="text-muted mb-0">Belum ada ujian.</p><?php else: ?><?php foreach ($ujian as $item): ?><div class="border rounded-3 p-3 mb-3"><div class="fw-semibold"><?= esc($item['judul_ujian']) ?></div><div class="small text-muted mt-1"><?= esc($item['keterangan'] ?: 'Tanpa keterangan') ?></div><div class="small text-warning mt-2"><i class="fa-regular fa-clock me-1"></i><?= !empty($item['deadline']) ? esc(date('d M Y, H:i', strtotime($item['deadline']))) : 'Tanpa deadline' ?></div></div><?php endforeach; ?><?php endif; ?></div></div><div class="col-lg-6"><div class="assessment-panel bg-white p-4 h-100"><h5 class="fw-bold mb-3"><i class="fa-solid fa-list-check me-2 text-success"></i>Daftar Tugas</h5><?php if (empty($tugas)): ?><p class="text-muted mb-0">Belum ada tugas.</p><?php else: ?><?php foreach ($tugas as $item): ?><div class="border rounded-3 p-3 mb-3"><div class="fw-semibold"><?= esc($item['judul_tugas']) ?></div><div class="small text-muted mt-1"><?= esc($item['deskripsi'] ?: 'Tanpa keterangan') ?></div><div class="small text-warning mt-2"><i class="fa-regular fa-clock me-1"></i><?= !empty($item['deadline']) ? esc(date('d M Y, H:i', strtotime($item['deadline']))) : 'Tanpa deadline' ?></div></div><?php endforeach; ?><?php endif; ?></div></div></div>
<?= $this->endSection() ?>
